# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - EicocElderPrayers

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: npm install, build, and test
        run: |
          npm ci
          npm run build --if-present
          #npm run test --if-present

      - name: Archive production artifacts
        run: tar --exclude='./node_modules' --exclude='./FunctionAppCode' -czf release.tar.gz ./* 

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.tar.gz

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Extract artifact
        run: tar -xzf release.tar.gz

      - name: Replace placeholders in api.js for development
        if: github.ref != 'refs/heads/main'
        run: |
          sed -i 's|GETPRAYER_ADDRESS|https://eicocelderprayerfunc.azurewebsites.net/api/GetAllPrayerRequests|g' ./routes/api.js
          sed -i 's|NEWPRAYER_ADDRESS|https://eicocelderprayerfunc.azurewebsites.net/api/CreateNewPrayerRequest?code=q0P7OkHKRTtLfygOfK1suAoRG62rAI9xFKiJFaJcwidwAzFumf8UIg%3D%3D|g' ./routes/api.js
          sed -i 's|UPDATEPRAYER_ADDRESS|https://eicocelderprayerfunc.azurewebsites.net/api/UpdatePrayerRequest?code=q0P7OkHKRTtLfygOfK1suAoRG62rAI9xFKiJFaJcwidwAzFumf8UIg%3D%3D|g' ./routes/api.js
          sed -i 's|UPLOAD_ATTENDANCE|https://eicocelderprayerfunc.azurewebsites.net/api/UploadAttendance|g' ./routes/api.js
          sed -i 's|GET_ATTENDANCE|https://eicocelderprayerfunc.azurewebsites.net/api/GetAttendanceRecords|g' ./routes/api.js

      - name: Replace placeholders in api.js for production
        if: github.ref == 'refs/heads/main'
        run: |
          sed -i 's|GETPRAYER_ADDRESS|https://eicocelderprayerfunc.azurewebsites.net/api/GetAllPrayerRequests|g' ./routes/api.js
          sed -i 's|NEWPRAYER_ADDRESS|https://eicocelderprayerfunc.azurewebsites.net/api/CreateNewPrayerRequest?code=q0P7OkHKRTtLfygOfK1suAoRG62rAI9xFKiJFaJcwidwAzFumf8UIg%3D%3D|g' ./routes/api.js
          sed -i 's|UPDATEPRAYER_ADDRESS|https://eicocelderprayerfunc.azurewebsites.net/api/UpdatePrayerRequest?code=q0P7OkHKRTtLfygOfK1suAoRG62rAI9xFKiJFaJcwidwAzFumf8UIg%3D%3D|g' ./routes/api.js
          sed -i 's|UPLOAD_ATTENDANCE|https://eicocelderprayerfunc.azurewebsites.net/api/UploadAttendance|g' ./routes/api.js
          sed -i 's|GET_ATTENDANCE|https://eicocelderprayerfunc.azurewebsites.net/api/GetAttendanceRecords|g' ./routes/api.js

      - name: Display api.js contents
        run: cat ./routes/api.js
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_425AA46F3A22494AB036876E8324571C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7A9DC43A4AFF48B9A6B9CC4AC1116180 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D680BD1857E14B9DAFDEA5CA77F45106 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'EicocElderPrayers'
          slot-name: 'Production'
          package: .
          