name: Build and deploy Node.js app to Azure Web App - EicocPrayers

on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: npm install, build, and test
        run: |
          npm ci
          npm run build --if-present
          #npm run test --if-present

      - name: Archive production artifacts
        run: tar -czf release.tar.gz ./*

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.tar.gz

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Extract artifact
        run: tar -xzf release.tar.gz

      - name: Set environment variable for API address (development)
        run: echo "GETPRAYER_ADDRESS=https://eicocprayerfunc.azurewebsites.net/api/GetAllPrayerRequests" >> $GITHUB_ENV
        run: echo "NEWPRAYER_ADDRESS=https://eicocprayerfunc.azurewebsites.net/api/CreateNewPrayerRequest" >> $GITHUB_ENV
        run: echo "UPDATEPRAYER_ADDRESS=https://eicocprayerfunc.azurewebsites.net/api/UpdatePrayerRequest?" >> $GITHUB_ENV
        if: github.ref != 'refs/heads/main'

      - name: Set environment variable for API address (production)
        run: echo "API_ADDRESS=https://eicocelderprayerfunc.azurewebsites.net" >> $GITHUB_ENV
        if: github.ref == 'refs/heads/main'

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A70AF8D4AA0D4D99BB64C9A399592BD5 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_48802C9470D0418A8CDBFB27B4E63667 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_5FA691B3879046CA87C1656DF9660040 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'EicocPrayers'
          slot-name: 'Production'
          package: .
